# Generated by Django 6.0.3 on 2026-04-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=60)),
                ('student_class', models.CharField(max_length=60)),
                ('section', models.CharField(max_length=60)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
